name: Build , test and deploy react app
on: push 
jobs: 
    React_testing: 
        runs-on: ubuntu-latest
        steps:
            - name: check out the code
              uses: actions/checkout@v6

            - name: install node js 
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: print node version
              run: node -v 

            - name: install dependencies
              run: npm ci

            - name: Run test cases 
              run : npm run test

